
-- --------------------------------------------------------

--
-- Structure for view `agloa_active_team_competitions_pivoted`
--
DROP TABLE IF EXISTS `agloa_active_team_competitions_pivoted`;

DROP VIEW IF EXISTS `agloa_active_team_competitions_pivoted`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `agloa_active_team_competitions_pivoted`  AS SELECT `agloa_active_team_competitions`.`team_id` AS `team_id`, concat(`agloa_active_team_competitions`.`EQ`,'EQ') AS `competition` FROM `agloa_active_team_competitions` WHERE (`agloa_active_team_competitions`.`EQ` <> '')union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`OS`,'OS') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`OS` <> '') union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`LI`,'LI') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`LI` <> '') union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`PROP`,'PROP') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`PROP` <> '') union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`PREZ`,'PREZ') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`PREZ` <> '') union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`WE`,'WE') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`WE` <> '') union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`CE`,'CE') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`CE` <> '') union select `agloa_active_team_competitions`.`team_id` AS `team_id`,concat(`agloa_active_team_competitions`.`WFF`,'WFF') AS `competition` from `agloa_active_team_competitions` where (`agloa_active_team_competitions`.`WFF` <> '')  ;
