
-- --------------------------------------------------------

--
-- Structure for view `teams_w_o_competitions`
--
DROP TABLE IF EXISTS `teams_w_o_competitions`;

DROP VIEW IF EXISTS `teams_w_o_competitions`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `teams_w_o_competitions`  AS SELECT `active_team_data`.`team_id` AS `team_id`, `active_team_data`.`title` AS `title`, `active_team_data`.`created_by` AS `created_by`, `active_team_data`.`modified_by` AS `modified_by`, `active_team_data`.`id` AS `id`, `active_team_data`.`entity_id` AS `entity_id`, `active_team_data`.`equations_21` AS `equations_21`, `active_team_data`.`on_sets_22` AS `on_sets_22`, `active_team_data`.`linguishtik_23` AS `linguishtik_23`, `active_team_data`.`propaganda_24` AS `propaganda_24`, `active_team_data`.`presidents_25` AS `presidents_25`, `active_team_data`.`world_events_26` AS `world_events_26`, `active_team_data`.`wff_n_proof_27` AS `wff_n_proof_27`, `active_team_data`.`district_equations_seed_29` AS `district_equations_seed_29`, `active_team_data`.`league_equations_seed_30` AS `league_equations_seed_30`, `active_team_data`.`district_on_sets_seed_31` AS `district_on_sets_seed_31`, `active_team_data`.`league_on_sets_seed_32` AS `league_on_sets_seed_32`, `active_team_data`.`district_linguishtik_seed_33` AS `district_linguishtik_seed_33`, `active_team_data`.`league_linguishtik_seed_34` AS `league_linguishtik_seed_34`, `active_team_data`.`district_wff_n_proof_seed_35` AS `district_wff_n_proof_seed_35`, `active_team_data`.`league_wff_n_proof_seed_36` AS `league_wff_n_proof_seed_36`, `active_team_data`.`current_events_74` AS `current_events_74`, `active_team_data`.`equations_section_75` AS `equations_section_75`, `active_team_data`.`on_sets_section_76` AS `on_sets_section_76`, `active_team_data`.`linguishtik_section_77` AS `linguishtik_section_77`, `active_team_data`.`wff_n_proof_section_78` AS `wff_n_proof_section_78` FROM `active_team_data` WHERE ((`active_team_data`.`equations_21` = '') AND (`active_team_data`.`on_sets_22` = '') AND (`active_team_data`.`linguishtik_23` = '') AND (`active_team_data`.`propaganda_24` = '') AND (`active_team_data`.`presidents_25` = '') AND (`active_team_data`.`world_events_26` = '') AND (`active_team_data`.`wff_n_proof_27` = '') AND (`active_team_data`.`current_events_74` = '')) ;
