
-- --------------------------------------------------------

--
-- Structure for view `agloa_teams_w_o_games`
--
DROP TABLE IF EXISTS `agloa_teams_w_o_games`;

DROP VIEW IF EXISTS `agloa_teams_w_o_games`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `agloa_teams_w_o_games`  AS SELECT `agloa_latest_active_team_player_data`.`team_id` AS `team_id`, `agloa_latest_active_team_player_data`.`team_name` AS `team_name`, `agloa_latest_active_team_player_data`.`created_by` AS `created_by`, `agloa_latest_active_team_player_data`.`modified_by` AS `modified_by`, `agloa_latest_active_team_player_data`.`team_EQ` AS `team_EQ`, `agloa_latest_active_team_player_data`.`team_OS` AS `team_OS`, `agloa_latest_active_team_player_data`.`team_LI` AS `team_LI`, `agloa_latest_active_team_player_data`.`team_PROP` AS `team_PROP`, `agloa_latest_active_team_player_data`.`team_PREZ` AS `team_PREZ`, `agloa_latest_active_team_player_data`.`team_THEME` AS `team_THEME`, `agloa_latest_active_team_player_data`.`team_CE` AS `team_CE`, `agloa_latest_active_team_player_data`.`team_WFF` AS `team_WFF`, `agloa_latest_active_team_player_data`.`player_id` AS `player_id`, `agloa_latest_active_team_player_data`.`player_name` AS `player_name`, `agloa_latest_active_team_player_data`.`player_EQ` AS `player_EQ`, `agloa_latest_active_team_player_data`.`Player_OS` AS `Player_OS`, `agloa_latest_active_team_player_data`.`player_LI` AS `player_LI`, `agloa_latest_active_team_player_data`.`player_PROP` AS `player_PROP`, `agloa_latest_active_team_player_data`.`player_PREZ` AS `player_PREZ`, `agloa_latest_active_team_player_data`.`player_theme` AS `player_theme`, `agloa_latest_active_team_player_data`.`player_CE` AS `player_CE`, `agloa_latest_active_team_player_data`.`player_WFF` AS `player_WFF` FROM `agloa_latest_active_team_player_data` WHERE ((`agloa_latest_active_team_player_data`.`team_EQ` is null) AND (`agloa_latest_active_team_player_data`.`team_OS` is null) AND (`agloa_latest_active_team_player_data`.`team_LI` is null) AND (`agloa_latest_active_team_player_data`.`team_PROP` is null) AND (`agloa_latest_active_team_player_data`.`team_PREZ` is null) AND (`agloa_latest_active_team_player_data`.`team_THEME` is null) AND (`agloa_latest_active_team_player_data`.`team_CE` is null) AND (`agloa_latest_active_team_player_data`.`team_WFF` is null)) ;
