
-- --------------------------------------------------------

--
-- Structure for view `agloa_game_division_count`
--
DROP TABLE IF EXISTS `agloa_game_division_count`;

DROP VIEW IF EXISTS `agloa_game_division_count`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `agloa_game_division_count`  AS SELECT 'EQ' AS `game`, `agloa_latest_active_player_data`.`EQ` AS `division`, count(`agloa_latest_active_player_data`.`EQ`) AS `count` FROM `agloa_latest_active_player_data` GROUP BY `agloa_latest_active_player_data`.`EQ` HAVING (`agloa_latest_active_player_data`.`EQ` <> '')union select 'OS' AS `game`,`agloa_latest_active_player_data`.`OS` AS `division`,count(`agloa_latest_active_player_data`.`OS`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`OS` having (`agloa_latest_active_player_data`.`OS` <> '') union select 'LI' AS `game`,`agloa_latest_active_player_data`.`LI` AS `division`,count(`agloa_latest_active_player_data`.`LI`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`LI` having (`agloa_latest_active_player_data`.`LI` <> '') union select 'PROP' AS `game`,`agloa_latest_active_player_data`.`PROP` AS `division`,count(`agloa_latest_active_player_data`.`PROP`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`PROP` having (`agloa_latest_active_player_data`.`PROP` <> '') union select 'PREZ' AS `game`,`agloa_latest_active_player_data`.`PREZ` AS `division`,count(`agloa_latest_active_player_data`.`PREZ`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`PREZ` having (`agloa_latest_active_player_data`.`PREZ` <> '') union select 'Theme' AS `game`,`agloa_latest_active_player_data`.`WE` AS `division`,count(`agloa_latest_active_player_data`.`WE`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`WE` having (`agloa_latest_active_player_data`.`WE` <> '') union select 'CE' AS `game`,`agloa_latest_active_player_data`.`CE` AS `division`,count(`agloa_latest_active_player_data`.`CE`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`CE` having (`agloa_latest_active_player_data`.`CE` <> '') union select 'WFF' AS `game`,`agloa_latest_active_player_data`.`WFF` AS `division`,count(`agloa_latest_active_player_data`.`WFF`) AS `count` from `agloa_latest_active_player_data` group by `agloa_latest_active_player_data`.`WFF` having (`agloa_latest_active_player_data`.`WFF` <> '')  ;
