
-- --------------------------------------------------------

--
-- Structure for view `player_competition_type`
--
DROP TABLE IF EXISTS `player_competition_type`;

DROP VIEW IF EXISTS `player_competition_type`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `player_competition_type`  AS SELECT `latest_active_player_data`.`contact_id` AS `contact_id`, `latest_active_player_data`.`sort_name` AS `sort_name`, concat(`latest_active_player_data`.`equations_11`,'EQ') AS `competition`, 'Equations' AS `competition_type` FROM `latest_active_player_data` WHERE (`latest_active_player_data`.`equations_11` <> '')union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`on_sets_12`,'OS') AS `competition`,'On-Sets' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`on_sets_12` <> '') union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`linguishtik_13`,'LI') AS `competition`,'LinguiSHTIK' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`linguishtik_13` <> '') union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`propaganda_14`,'PROP') AS `competition`,'Propaganda' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`propaganda_14` <> '') union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`presidents_15`,'PREZ') AS `competition`,'Presidents' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`presidents_15` <> '') union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`world_events_16`,'WE') AS `competition`,'Theme' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`world_events_16` <> '') union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`current_events_56`,'CE') AS `competition`,'Current Events' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`current_events_56` <> '') union select `latest_active_player_data`.`contact_id` AS `contact_id`,`latest_active_player_data`.`sort_name` AS `sort_name`,concat(`latest_active_player_data`.`wff_n_proof_17`,'WFF') AS `competition`,'Wff \'N Proof' AS `competition_type` from `latest_active_player_data` where (`latest_active_player_data`.`wff_n_proof_17` <> '')  ;
