
-- --------------------------------------------------------

--
-- Structure for view `agloa_active_team_competitions`
--
DROP TABLE IF EXISTS `agloa_active_team_competitions`;

DROP VIEW IF EXISTS `agloa_active_team_competitions`;
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `agloa_active_team_competitions`  AS SELECT `active_team_data`.`team_id` AS `team_id`, `active_team_data`.`title` AS `team_name`, `active_team_data`.`created_id` AS `created_id`, `active_team_data`.`created_by` AS `created_by`, `active_team_data`.`modified_id` AS `modified_id`, `active_team_data`.`modified_by` AS `modified_by`, `active_team_data`.`registration_group_id` AS `registration_group_id`, `active_team_data`.`registration_group` AS `registration_group`, `active_team_data`.`equations_21` AS `EQ`, `active_team_data`.`on_sets_22` AS `OS`, `active_team_data`.`linguishtik_23` AS `LI`, `active_team_data`.`propaganda_24` AS `PROP`, `active_team_data`.`presidents_25` AS `PREZ`, `active_team_data`.`world_events_26` AS `WE`, `active_team_data`.`wff_n_proof_27` AS `WFF`, `active_team_data`.`current_events_74` AS `CE`, `active_team_data`.`district_equations_seed_29` AS `district_equations_seed`, `active_team_data`.`league_equations_seed_30` AS `league_equations_seed`, `active_team_data`.`district_on_sets_seed_31` AS `district_on_sets_seed`, `active_team_data`.`league_on_sets_seed_32` AS `league_on_sets_seed`, `active_team_data`.`district_linguishtik_seed_33` AS `district_linguishtik_seed`, `active_team_data`.`league_linguishtik_seed_34` AS `league_linguishtik_seed`, `active_team_data`.`district_wff_n_proof_seed_35` AS `district_wff_n_proof_seed`, `active_team_data`.`league_wff_n_proof_seed_36` AS `league_wff_n_proof_seed`, `active_team_data`.`equations_section_75` AS `equations_section`, `active_team_data`.`on_sets_section_76` AS `on_sets_section`, `active_team_data`.`linguishtik_section_77` AS `linguishtik_section`, `active_team_data`.`wff_n_proof_section_78` AS `wff_n_proof_section`, concat(if((`active_team_data`.`equations_21` <> ''),left(`active_team_data`.`equations_21`,1),'_'),if((`active_team_data`.`on_sets_22` <> ''),left(`active_team_data`.`on_sets_22`,1),'_'),if((`active_team_data`.`linguishtik_23` <> ''),left(`active_team_data`.`linguishtik_23`,1),'_'),if((`active_team_data`.`propaganda_24` <> ''),left(`active_team_data`.`propaganda_24`,1),'_'),if((`active_team_data`.`presidents_25` <> ''),left(`active_team_data`.`presidents_25`,1),'_'),if((`active_team_data`.`world_events_26` <> ''),left(`active_team_data`.`world_events_26`,1),'_'),if((`active_team_data`.`wff_n_proof_27` <> ''),left(`active_team_data`.`wff_n_proof_27`,1),'_'),if((`active_team_data`.`current_events_74` <> ''),left(`active_team_data`.`current_events_74`,1),'_')) AS `competition_key` FROM `active_team_data` ;
